# Generated by Django 4.1 on 2022-09-01 01:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.country')),
            ],
        ),
        migrations.CreateModel(
            name='ValueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_material', models.CharField(blank=True, max_length=64, null=True)),
                ('case_material', models.CharField(blank=True, max_length=64, null=True)),
                ('case_thickness', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(128)])),
                ('case_width', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(128)])),
                ('description', models.TextField(blank=True, max_length=2048, null=True)),
                ('is_visible', models.BooleanField()),
                ('lug_to_lug', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(128)])),
                ('lug_width', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(128)])),
                ('model', models.CharField(blank=True, max_length=64, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(2048)])),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_list.brand')),
            ],
            options={
                'verbose_name_plural': 'watches',
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=2048, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_list.valuetype')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_list.watch')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=2048, null=True)),
                ('file', models.FileField(unique=True, upload_to='media')),
                ('is_visible', models.BooleanField()),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch_list.watch')),
            ],
        ),
    ]
