# Generated by Django 4.1 on 2022-09-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_list', '0002_movementtype_watch_reference_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='dial_description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
