# Generated by Django 4.1 on 2022-09-01 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch_list', '0003_watch_dial_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='watch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='watch_list.watch'),
        ),
    ]
