# Generated by Django 4.1 on 2022-09-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_list', '0004_alter_value_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='serial_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
