# Generated by Django 4.1.1 on 2022-09-07 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='created',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='country',
            name='created',
        ),
        migrations.RemoveField(
            model_name='country',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='materialtype',
            name='created',
        ),
        migrations.RemoveField(
            model_name='materialtype',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='movementtype',
            name='created',
        ),
        migrations.RemoveField(
            model_name='movementtype',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='valuetype',
            name='created',
        ),
        migrations.RemoveField(
            model_name='valuetype',
            name='modified',
        ),
    ]
