# Generated by Django 4.1.1 on 2022-09-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0002_remove_brand_created_remove_brand_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='is_visible',
        ),
    ]
